management:
  tracing:
    sampling:
      probability: 0.0
  endpoints:
    web:
      exposure:
        include: health, metrics, loggers
      base-path: /
      path-mapping:
        health: actuator/health
        metrics: actuator/metrics
        loggers: oc-capacity/actuator/loggers
  endpoint:
    health:
      probes:
        enabled: false
      show-details: "always"
  health:
    circuitbreakers:
      enabled: true
    diskspace:
      enabled: false
    r2dbc:
      enabled: true
    ping:
      enabled: false
    refresh:
      enabled: false
technology-mngr:
  base-url: "${TECHNOLOGY_MNGR_BASE_URL:http://localhost:8080/technology}"
  timeout: "500"
resilience4j.circuitbreaker:
  circuit-breaker-aspect-order: 1
  configs:
    default:
      register-health-indicator: true
  instances:
    technologyMngr:
      base-config: default
      failure-rate-threshold: 50
      slow-call-rate-threshold: 50
      slow-call-duration-threshold: 2s
      sliding-window-size: 5
      minimum-number-of-calls: 5
      wait-duration-in-open-state: 25s
      max-wait-duration-in-half-open-state: 5s
      permitted-number-of-calls-in-half-open-state: 2
      automatic-transition-from-open-to-half-open-enabled: false
      record-exceptions: java.util.concurrent.TimeoutException
      ignore-exceptions: com.onclass.capacity.domain.exceptions.BusinessException
resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 2000ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2.0
        maxWaitDuration: 10000ms  # Duraci칩n m치xima del backoff
        initialInterval: 500ms    # Intervalo inicial para el backoff
    instances:
      technologyMngrRetry:
        maxAttempts: 1
        waitDuration: 1000ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 1.5
        maxWaitDuration: 10000ms  # Duraci칩n m치xima del backoff
        initialInterval: 500ms    # Intervalo inicial para el backoff
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 10
        maxWaitDuration: 500ms
    instances:
      technologyMngrBulkhead:
        maxConcurrentCalls: 5
        maxWaitDuration: 1s